name: Check links
on: [pull_request]
jobs:
  check-links:
    name: runner / htmltest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
