sequenceDiagram
    participant Spec as Model checker
    participant Harness
    participant Impl as Implementation

    loop for steps i in 0..n
        Harness->>Spec: i. assumeTransition t_i
        Spec-->>Harness: sat
        Harness->>Spec: nextStep & query
        Spec-->>Harness: semi-concrete trace

        Harness->>Impl: execute action i
        Impl-->>Harness: response i
        Harness->>Spec: i+1. assumeState from response i
        Spec-->>Harness: sat
    end


    Note right of Harness: if assumeState returns unsat,
    Note right of Harness: then report divergence

